### ISSUE TITLE
Clock Informer unreachable after update 2.3.5

### ISSUE THREAD

**Issue by Ianszh** [vortigont/infoclock#1]
I can no longer reach Clock informer, the IP is correct it tries to connect but after a few minutes there's an unreachable error!

**Comment by vortigont** [comment]
Sorry, what is `2.3.5`?
On startup it will scroll it's IP address if connection is successful. Do you see that message?
You can try to ping that IP to check if it's reachable.

**Comment by Ianszh** [comment]
2.3.5 is the firmware version running on clock informer, according to the clock informer startup 2.3.6 is the latest.

I've pinged and it definitely reachable, all I get is a white screen.

**Comment by vortigont** [comment]
How do you find this version number?
Actually current version of Informer in repo is `1.2.1` and EmbUI framework version is `2.6.3`
Have you uploaded FS image with data files to your board?

**Comment by Ianszh** [comment]
I just installed the basic installer.
I get the Firmware version at startup after the IP address, here's some images.
Is there another Clock Informer?

![IMG_4752](https://github.com/vortigont/infoclock/assets/4294446/52f05ce2-03da-4a08-97e7-6a23603299c8)
![IMG_4753](https://github.com/vortigont/infoclock/assets/4294446/4eb02c95-4392-4683-bbc3-def5f470faab)
![IMG_4757](https://github.com/vortigont/infoclock/assets/4294446/c4cc0a1a-37be-4650-9207-bd729c286f6b)

**Comment by vortigont** [comment]
that is definitely not my project. Mine is meant to run 4x4 matrix modules, square pane. Like in a video on main page.

**Comment by Ianszh** [comment]
Oops, how embarrassing sorry for the confusion.

**Comment by vortigont** [comment]
No problem :))
